eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPath}/health
spring:
  application:
    name: provider  ## 应用程序名称，后面会在消费者中用到
server:
  port: 8000